#!/usr/bin/env node

var app = require("commander")
var Dabble = require("./src/dabble")

app
  .version('0.0.1')
  .option('-s, --save <filename>','A filename', Dabble.save)

app
  .parse(process.argv)